### ISSUE TITLE
Exception on the rebind.network website

### ISSUE THREAD

**Issue by akatasonov** [brannondorsey/dns-rebind-toolkit#4]
![image](https://user-images.githubusercontent.com/6917547/60980738-b1a19500-a33d-11e9-860a-30fe22c1565f.png)

**Comment by rumpeltux** [comment]
Similar here: 
![image](https://user-images.githubusercontent.com/200124/62428803-3a75db80-b706-11e9-9e25-fda3bdeeb37e.png)

**Comment by CaptainMcCrank** [comment]
I'm guessing this is broken for everyone?  

I'm also getting the null SDP error.  
<img width="1166" alt="Screen Shot 2019-09-30 at 2 59 56 PM" src="https://user-images.githubusercontent.com/31334/65920143-109e0580-e393-11e9-9032-a32897efd671.png">

**Comment by brannondorsey** [comment]
I've just pushed two commits which should resolve these issues. The method we use to detect local IP addresses via WebRTC looks outdated and I don't think it works in modern browsers. I might fix that in the future, but at least we no longer see the null/undefined error @CaptainMcCrank mentioned.

Thanks for your patience all. This repo isn't really maintained anymore.
